export const FALLBACK_JOBS_DB = [
            // --- 4 HORAS (PART-TIME / PASANTÍAS) ---
            {
                id: "linkedin-grant-thornton-ciberseguridad",
                company: "Grant Thornton Uruguay",
                title: "Pasante en Ciberseguridad & Auditoría de Sistemas",
                hours: "4h",
                hoursLabel: "4 horas diarias (Lunes a Viernes)",
                modality: "Híbrido / Presencial",
                modalityKey: "hybrid",
                sector: "consulting",
                sectorLabel: "Consultoría & Auditoría IT",
                domain: "CYBERSECURITY",
                domainLabel: "Ciberseguridad & Auditoría IT",
                criticalSkills: ["ciberseguridad", "iso 27001", "auditoría de sistemas", "controles it"],
                location: "Montevideo",
                desc: "Pasantía de 3 meses en la firma internacional Grant Thornton. Carga horaria de 4 horas diarias de lunes a viernes. Relevamiento de procesos tecnológicos, controles de seguridad y soporte analítico.",
                careerFit: ["Negocios Digitales", "Sistemas", "Ingeniería", "Administración"],
                requirements: {
                    mandatory: ["Segundo año universitario aprobado", "Disponibilidad 4 horas diarias"],
                    desirable: ["Interés en ciberseguridad y auditoría", "Manejo de herramientas analíticas"],
                    bonus: ["Conocimientos de bases de datos", "Inglés intermedio"]
                },
                salaryGuide: "$22.000 - $28.000 UYU (Pasantía 4h)",
                applyUrl: "https://uy.linkedin.com/jobs/view/pasante-en-ciberseguridad-at-grant-thornton-uruguay-4464220434",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "linkedin-prota-admin-parttime",
                company: "Prota (Consultora RRHH)",
                title: "Administrativa Jr Part-Time (4 a 6 horas)",
                hours: "4h",
                hoursLabel: "4 a 6 horas (A convenir de 9 a 18 hs)",
                modality: "Presencial (Centro)",
                modalityKey: "presential",
                sector: "consulting",
                sectorLabel: "Administración & Soporte",
                domain: "BUSINESS_ADMIN",
                domainLabel: "Negocios & Administración",
                criticalSkills: ["facturación", "gestión administrativa", "archivo", "planillas"],
                location: "Montevideo Centro",
                desc: "Puesto Part-Time de 4 a 6 horas diarias de lunes a viernes coordinables. Contrato a término por 1 año con opción a renovación. Tareas: facturación, planillas de cálculo y archivo.",
                careerFit: ["Administración", "Ciencias Económicas", "Negocios Digitales"],
                requirements: {
                    mandatory: ["Estudiante universitario de Administración o carreras afines", "Manejo de Excel"],
                    desirable: ["Inglés intermedio", "Experiencia previa administrativa"],
                    bonus: ["Manejo de ERP o herramientas contables"]
                },
                salaryGuide: "$24.000 - $32.000 UYU (según horas acordadas)",
                applyUrl: "https://uy.linkedin.com/jobs/view/administrativa-part-time-at-prota-4465221749",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "linkedin-bestseller-student-worker",
                company: "BESTSELLER (Multinacional Retail)",
                title: "Student Worker (Comercial & Base de Datos)",
                hours: "4h",
                hoursLabel: "Part-Time / Horario Estudiante",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "retail",
                sectorLabel: "Retail & Moda Global",
                domain: "DATA_BI",
                domainLabel: "Datos & Soporte Comercial",
                criticalSkills: ["bases de datos", "reportes", "excel", "e-commerce"],
                location: "Montevideo",
                desc: "Vacante Part-Time en BESTSELLER (Jack & Jones, Only, Vero Moda). Soporte al área comercial en actualización de bases de datos, generación de reportes y carga de órdenes.",
                careerFit: ["Negocios Digitales", "Administración", "Economía", "Ingeniería"],
                requirements: {
                    mandatory: ["Estudiante de 1er o 2do año universitario", "Dominio de Excel"],
                    desirable: ["Inglés intermedio (compañía internacional)", "Habilidades de reporte"],
                    bonus: ["Conocimiento de retail o e-commerce"]
                },
                salaryGuide: "$26.000 - $32.000 UYU (Régimen estudiante)",
                applyUrl: "https://uy.linkedin.com/jobs/view/student-worker-contrato-a-t%C3%A9rmino-at-bestseller-4462451747",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "ort-portal-empleo",
                company: "Universidad ORT Uruguay",
                title: "Bolsa de Empleo & Pasantías Exclusivas para Alumnos ORT",
                hours: "4h",
                hoursLabel: "4 a 6 horas (Convenios Académicos)",
                modality: "Presencial / Híbrido",
                modalityKey: "presential",
                sector: "univ",
                sectorLabel: "Bolsa Universitaria",
                domain: "BUSINESS_ADMIN",
                domainLabel: "Convenios Universitarios ORT",
                criticalSkills: ["estudiante ort", "negocios digitales", "analítica"],
                location: "Montevideo",
                desc: "Portal oficial de convenios de pasantía académica de ORT Uruguay. Acceso exclusivo a ofertas part-time de empresas socias que coordinan horarios con la facultad.",
                careerFit: ["Negocios Digitales", "Sistemas", "Administración", "Analítica"],
                requirements: {
                    mandatory: ["Ser estudiante activo o graduado de Universidad ORT Uruguay"],
                    desirable: ["Escolaridad destacada"],
                    bonus: ["Nivel B2 de inglés"]
                },
                salaryGuide: "Regulado por convenios universitarios de pasantía",
                applyUrl: "https://empleo.ort.edu.uy/",
                isLinkedIn: false,
                isTalentPool: true
            },

            // --- 6 HORAS (MEDIA JORNADA / BANCA & TECH) ---
            {
                id: "linkedin-pento-ai-trainee",
                company: "Pento (AI & Software)",
                title: "AI Developer Trainee — 6 horas diarias",
                hours: "6h",
                hoursLabel: "6 horas diarias (Modalidad Híbrida)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "tech",
                sectorLabel: "Tecnología & IA",
                domain: "SOFTWARE_DEV",
                domainLabel: "Desarrollo de Software & IA",
                criticalSkills: ["javascript", "react", "apis", "git", "backend"],
                location: "Montevideo",
                desc: "Programa formativo Trainee de 6 horas diarias en empresa enfocada en soluciones de inteligencia artificial. Aprendizaje práctico en modelos, desarrollo y programación de aplicaciones.",
                careerFit: ["Sistemas", "Ingeniería en Computación", "Ciencia de Datos"],
                requirements: {
                    mandatory: ["Estudiante de Sistemas o Computación", "Fundamentos sólidos de desarrollo web y lógica de programación", "Inglés intermedio/avanzado"],
                    desirable: ["Nociones de Python o JavaScript", "Curiosidad por IA generativa"],
                    bonus: ["Proyectos personales o GitHub"]
                },
                salaryGuide: "$30.000 - $38.000 UYU (Trainee 6h)",
                applyUrl: "https://uy.linkedin.com/jobs/view/ai-developer-trainee-at-pento-4465228447",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "linkedin-quantik-pasante-ti",
                company: "Quantik Group",
                title: "Pasante de TI & Soporte de Plataformas — 6 horas",
                hours: "6h",
                hoursLabel: "6 horas diarias (Lunes a Viernes)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "tech",
                sectorLabel: "Telecomunicaciones & Software",
                domain: "IT_SUPPORT_INFRA",
                domainLabel: "Soporte TI & Infraestructura",
                criticalSkills: ["linux", "redes", "hardware", "active directory", "soporte técnico", "mesa de ayuda"],
                location: "Montevideo",
                desc: "Pasantía de 6 horas diarias de lunes a viernes en Quantik Group. Mesa de ayuda a usuarios corporativos, diagnóstico de hardware, configuración de sistemas operativos Linux/Windows y redes locales.",
                careerFit: ["Sistemas", "Redes & Telecomunicaciones", "Tecnología de la Información"],
                requirements: {
                    mandatory: ["Estudiante de carreras de Sistemas o Redes", "Conocimientos de hardware, redes o mesa de ayuda (excluyente)", "Disponibilidad 6 horas"],
                    desirable: ["Administración básica de Linux", "Vocación de servicio técnico"],
                    bonus: ["Certificaciones Cisco o soporte de telecomunicaciones"]
                },
                salaryGuide: "$28.000 - $35.000 UYU",
                applyUrl: "https://uy.linkedin.com/jobs/view/pasante-de-ti-at-quantik-group-4461373330",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "linkedin-pwc-junior-auditoria",
                company: "PwC Uruguay",
                title: "Junior — Auditoría Externa (Régimen Part-Time)",
                hours: "6h",
                hoursLabel: "6 horas / Part-time formal",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "consulting",
                sectorLabel: "Consultoría & Auditoría",
                domain: "FINANCE_BANKING",
                domainLabel: "Auditoría Contable & Finanzas",
                criticalSkills: ["auditoría contable", "contabilidad", "control interno", "ciencias económicas"],
                location: "Montevideo",
                desc: "Puesto Part-Time formal en PwC Uruguay para estudiantes universitarios con licencias de estudio. Revisión analítica de operaciones, análisis de procesos contables y control interno.",
                careerFit: ["Contabilidad", "Administración", "Economía", "Negocios"],
                requirements: {
                    mandatory: ["Estudiante universitario con al menos 50% de avance académico en Ciencias Económicas", "No requiere experiencia previa"],
                    desirable: ["Inglés intermedio", "Manejo fluido de Excel"],
                    bonus: ["Capacidad analítica y trabajo en equipo"]
                },
                salaryGuide: "$32.000 - $42.000 UYU + Beneficios Big Four",
                applyUrl: "https://uy.linkedin.com/jobs/view/junior-auditor%C3%ADa-externa-contable-at-pwc-uruguay-4465656096",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "linkedin-meli-customer-experience",
                company: "Mercado Libre Uruguay",
                title: "Representante de Customer Experience — 6 horas",
                hours: "6h",
                hoursLabel: "6 horas diarias (Turno fijo)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "tech",
                sectorLabel: "E-commerce & Fintech",
                domain: "OPERATIONS_LOG",
                domainLabel: "Operaciones & Customer Experience",
                criticalSkills: ["customer experience", "atención al cliente", "e-commerce", "resolución de incidentes"],
                location: "WTC Montevideo",
                desc: "Atención y soporte a usuarios de Mercado Libre y Mercado Pago en WTC Free Zone. Resolución de consultas sobre pagos digitales, cobros y envíos.",
                careerFit: ["Negocios Digitales", "Administración", "Comunicación"],
                requirements: {
                    mandatory: ["Secundario completo / estudiante universitario", "Disponibilidad 6 horas"],
                    desirable: ["Excelente redacción y empatía", "Manejo de herramientas digitales"],
                    bonus: ["Experiencia en plataformas de e-commerce o atención"]
                },
                salaryGuide: "$35.000 - $45.000 UYU + Almuerzo y prepaga",
                applyUrl: "https://uy.linkedin.com/jobs/view/representante-de-customer-experience-at-mercado-libre-4454696054",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "linkedin-rua-operador-telefonico",
                company: "RUA Asistencia",
                title: "Operador de Servicios & Asistencia — 6 horas",
                hours: "6h",
                hoursLabel: "6 horas diarias (Horario fijo)",
                modality: "Presencial",
                modalityKey: "presential",
                sector: "retail",
                sectorLabel: "Servicios Corporativos",
                domain: "OPERATIONS_LOG",
                domainLabel: "Operaciones & Servicios",
                criticalSkills: ["atención telefónica", "gestión operativa", "resolución de incidentes"],
                location: "Montevideo",
                desc: "Jornada fija de 6 horas diarias para atención y coordinación de servicios solicitados por socios. Seguimiento de casos en plataformas informáticas.",
                careerFit: ["Administración", "General"],
                requirements: {
                    mandatory: ["Disponibilidad 6 horas diarias", "Manejo básico de Office"],
                    desirable: ["Experiencia en atención telefónica"],
                    bonus: ["Resolución rápida de incidentes"]
                },
                salaryGuide: "$25.000 - $30.000 UYU",
                applyUrl: "https://uy.linkedin.com/jobs/view/operador-telef%C3%B3nico-call-center-at-rua-asistencia-4466738461",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "itau-base-talentos",
                company: "Banco Itaú Uruguay",
                title: "Base de Talentos: Postulación Espontánea (Jornada 6h)",
                hours: "6h",
                hoursLabel: "6 horas (Jornada bancaria estándar)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "bank",
                sectorLabel: "Banca & Finanzas",
                domain: "FINANCE_BANKING",
                domainLabel: "Banca & Finanzas",
                criticalSkills: ["banca", "ciencias económicas", "análisis financiero", "servicios bancarios"],
                location: "Montevideo",
                desc: "Canal oficial para ingresar CV al sistema de Recursos Humanos de Itaú para futuras vacantes de 6 horas en áreas comerciales y operativas.",
                careerFit: ["Ciencias Económicas", "Negocios Digitales", "Administración"],
                requirements: {
                    mandatory: ["Estudiante universitario activo"],
                    desirable: ["Manejo de Excel y orientación analítica"],
                    bonus: ["Vocación de servicio comercial"]
                },
                salaryGuide: "$38.000 - $48.000 UYU (Beneficios bancarios AEBU)",
                applyUrl: "https://itau.evaluar.com/",
                isLinkedIn: false,
                isTalentPool: true
            },
            {
                id: "santander-operador-atencion",
                company: "Banco Santander Uruguay",
                title: "Operador de Servicios & Asistencia Bancaria — 6 horas",
                hours: "6h",
                hoursLabel: "6 horas diarias (Lunes a Viernes)",
                modality: "Presencial",
                modalityKey: "presential",
                sector: "bank",
                sectorLabel: "Banca & Finanzas",
                domain: "FINANCE_BANKING",
                domainLabel: "Banca Comercial & Servicios",
                criticalSkills: ["servicios bancarios", "atención financiera", "caja", "operaciones bancarias"],
                location: "Montevideo",
                desc: "Jornada bancaria de 6 horas para atención comercial y operativa a clientes de Banco Santander. Excelente clima y proyección en el sector financiero.",
                careerFit: ["Administración", "Economía", "Negocios Digitales"],
                requirements: {
                    mandatory: ["Estudiante de carreras universitarias", "Disponibilidad 6 horas"],
                    desirable: ["Manejo de herramientas informáticas"],
                    bonus: ["Experiencia previa en atención al público"]
                },
                salaryGuide: "$36.000 - $45.000 UYU (Convenio bancario)",
                applyUrl: "https://santander.com.uy/institucional/trabaja-con-nosotros",
                isLinkedIn: false,
                isTalentPool: true
            },
            {
                id: "dlocal-careers-fintech",
                company: "dLocal FinTech",
                title: "Portal de Carreras & Pasantías Fintech Montevideo",
                hours: "6h",
                hoursLabel: "6 horas / Horario Flexible",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "tech",
                sectorLabel: "Fintech & Pagos Globales",
                domain: "DATA_BI",
                domainLabel: "Fintech, Pagos & Analítica",
                criticalSkills: ["sql", "pagos digitales", "fintech", "análisis de datos"],
                location: "Montevideo",
                desc: "Pasantías y oportunidades junior en el primer unicornio uruguayo. Equipos de operaciones financieras, análisis de transacciones cross-border y conciliaciones.",
                careerFit: ["Negocios Digitales", "Economía", "Sistemas", "Administración"],
                requirements: {
                    mandatory: ["Inglés avanzado/bilingüe (excluyente)", "Estudiante universitario"],
                    desirable: ["Manejo de SQL o analítica de datos"],
                    bonus: ["Curiosidad por la industria de pagos"]
                },
                salaryGuide: "$45.000 - $60.000 UYU",
                applyUrl: "https://dlocal.com/careers/",
                isLinkedIn: false,
                isTalentPool: true
            },

            // --- 8 HORAS (TIEMPO COMPLETO / JUNIOR) ---
            {
                id: "linkedin-cash-inteligencia-comercial",
                company: "CASH (Servicios Financieros)",
                title: "Analista de Inteligencia Comercial — SQL, Power BI, Excel",
                hours: "8h",
                hoursLabel: "8 horas diarias (Lunes a Viernes)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "bank",
                sectorLabel: "Finanzas & Crédito",
                domain: "DATA_BI",
                domainLabel: "Datos & Inteligencia Comercial",
                criticalSkills: ["sql", "power bi", "modelado de datos", "python", "analítica comercial"],
                location: "Montevideo",
                desc: "Extracción, análisis y modelado de datos para generar insights comerciales y tableros en Power BI/Tableau. Soporte al área de negocios.",
                careerFit: ["Negocios Digitales", "Estadística", "Economía", "Sistemas"],
                requirements: {
                    mandatory: ["Manejo avanzado de SQL y Power BI", "Perfil analítico comercial"],
                    desirable: ["Python para análisis de datos", "Experiencia en sector financiero"],
                    bonus: ["Modelado predictivo o credit scoring"]
                },
                salaryGuide: "$50.000 - $68.000 UYU (Full-time)",
                applyUrl: "https://uy.linkedin.com/jobs/view/analista-de-inteligencia-comercial-at-cash-4466412215",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "linkedin-farmashop-people-analytics",
                company: "Farmashop",
                title: "Asistente de People Analytics — Dashboards & KPIs",
                hours: "8h",
                hoursLabel: "8 horas (Lunes a Viernes)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "retail",
                sectorLabel: "Retail Farmacéutico",
                domain: "DATA_BI",
                domainLabel: "People Analytics & BI",
                criticalSkills: ["power bi", "sql", "kpis", "people analytics", "dashboards"],
                location: "Montevideo",
                desc: "Diseño, automatización y mantenimiento de tableros de gestión humana en Power BI. Análisis de indicadores de rotación, ausentismo y desempeño.",
                careerFit: ["Negocios Digitales", "Administración", "RRHH", "Analítica"],
                requirements: {
                    mandatory: ["Dominio de Power BI y Excel avanzado", "Estudiante avanzado o egresado"],
                    desirable: ["Experiencia en HR Analytics o tableros de gestión"],
                    bonus: ["SQL o visualización de datos"]
                },
                salaryGuide: "$45.000 - $58.000 UYU (Full-time)",
                applyUrl: "https://uy.linkedin.com/jobs/view/asistente-de-people-analytics-at-farmashop-4464229669",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "cpa-ferrere-analista-procesos",
                company: "CPA Ferrere",
                title: "Analista de Proceso y Negocios (Banca y Tecnología)",
                hours: "8h",
                hoursLabel: "8 horas (Tiempo Completo)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "consulting",
                sectorLabel: "Consultoría & Procesos",
                domain: "BUSINESS_ADMIN",
                domainLabel: "Consultoría de Negocios & Procesos",
                criticalSkills: ["análisis de procesos", "relevamiento", "banca", "metodologías ágiles"],
                location: "Montevideo",
                desc: "Relevamiento de requerimientos, diseño de flujos de procesos e implementación de soluciones tecnológicas bancarias en CPA Ferrere (ID 696909).",
                careerFit: ["Negocios Digitales", "Administración", "Ingeniería"],
                requirements: {
                    mandatory: ["Estudiante universitario avanzado", "Capacidad analítica de procesos"],
                    desirable: ["Inglés intermedio/avanzado", "Experiencia previa en proyectos"],
                    bonus: ["Conocimiento de banca o fintech"]
                },
                salaryGuide: "$48.000 - $65.000 UYU (Full-time)",
                applyUrl: "https://talento.cpaferrere.com/jobs/696909-analista-de-proceso-y-negocios",
                isLinkedIn: false,
                isTalentPool: false
            },
            {
                id: "cpa-ferrere-analista-jr-banca-tech",
                company: "CPA Ferrere",
                title: "Analista Junior en Banca y Tecnología",
                hours: "8h",
                hoursLabel: "8 horas (Tiempo Completo)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "consulting",
                sectorLabel: "Consultoría & Banca",
                domain: "BUSINESS_ADMIN",
                domainLabel: "Consultoría Tecnológica & Banca",
                criticalSkills: ["testing funcional", "software bancario", "relevamiento", "ciencias económicas"],
                location: "Montevideo",
                desc: "Relevamiento de requerimientos con clientes bancarios, testing funcional y apoyo en transformación tecnológica en CPA Ferrere (ID 696910).",
                careerFit: ["Administración", "Contabilidad", "Negocios Digitales"],
                requirements: {
                    mandatory: ["Estudiante avanzado de Ciencias Económicas", "Inglés intermedio/avanzado"],
                    desirable: ["Testing funcional o software bancario"],
                    bonus: ["Excel avanzado"]
                },
                salaryGuide: "$45.000 - $60.000 UYU (Full-time)",
                applyUrl: "https://talento.cpaferrere.com/jobs/696910-analista-junior-en-banca-y-tecnologia",
                isLinkedIn: false,
                isTalentPool: false
            },
            {
                id: "buscojobs-analista-funcional-nexit",
                company: "Nexit (vía BuscoJobs)",
                title: "Analista Funcional Jr (ERP & Consultoría)",
                hours: "8h",
                hoursLabel: "8 horas (Tiempo Completo: 9 a 18 hs)",
                modality: "Presencial / Híbrido",
                modalityKey: "presential",
                sector: "consulting",
                sectorLabel: "Consultoría & ERP",
                domain: "BUSINESS_ADMIN",
                domainLabel: "Consultoría ERP & Procesos",
                criticalSkills: ["erp", "parametrización", "relevamiento funcional", "procesos contables"],
                location: "Montevideo",
                desc: "Relevamiento de necesidades del cliente corporativo, parametrización y soporte sobre módulos de software de gestión ERP (ID 274020).",
                careerFit: ["Administración", "Negocios Digitales", "Contabilidad"],
                requirements: {
                    mandatory: ["Disponibilidad 9 a 18 hs", "Formación en administración o negocios"],
                    desirable: ["Nociones de sistemas ERP", "Excel analítico"],
                    bonus: ["Capacidad pedagógica con usuarios"]
                },
                salaryGuide: "$40.000 - $52.000 UYU (Full-time)",
                applyUrl: "https://www.buscojobs.com.uy/analista-funcional-jr-contador-lic-en-administracion-en-montevideo-ID-274020",
                isLinkedIn: false,
                isTalentPool: false
            },
            {
                id: "buscojobs-urudata-comercial-jr",
                company: "Urudata (vía BuscoJobs)",
                title: "Ejecutivo Comercial Junior / Business Tech",
                hours: "8h",
                hoursLabel: "8 horas (Tiempo Completo: 9 a 18 hs)",
                modality: "Presencial / Híbrido",
                modalityKey: "presential",
                sector: "tech",
                sectorLabel: "Tecnología Corporativa",
                domain: "MARKETING_ECOMM",
                domainLabel: "Comercial B2B & Negocios Tech",
                criticalSkills: ["ventas b2b", "negociación", "propuestas comerciales", "prospección"],
                location: "Montevideo",
                desc: "Gestión de cartera de clientes corporativos B2B y elaboración de propuestas de servicios de infraestructura IT (ID 276252).",
                careerFit: ["Negocios Digitales", "Administración", "Marketing"],
                requirements: {
                    mandatory: ["Perfil comercial B2B", "Disponibilidad 9 a 18 hs"],
                    desirable: ["Conocimiento de servicios cloud e IT"],
                    bonus: ["Habilidades de negociación"]
                },
                salaryGuide: "$42.000 - $55.000 UYU + Comisiones comerciales",
                applyUrl: "https://www.buscojobs.com.uy/ejecutivo-comercial-junior-en-montevideo-ID-276252",
                isLinkedIn: false,
                isTalentPool: false
            },
            {
                id: "advice-digital-media-finance",
                company: "Advice Recursos Humanos",
                title: "Digital Media Finance Analyst",
                hours: "8h",
                hoursLabel: "8 horas (Tiempo Completo)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "consulting",
                sectorLabel: "Consultora & Selección",
                domain: "FINANCE_BANKING",
                domainLabel: "Finanzas de Medios & Analítica",
                criticalSkills: ["conciliaciones financieras", "meta ads", "google ads", "control de gestión", "finanzas"],
                location: "Montevideo",
                desc: "Conciliaciones financieras de plataformas de medios digitales (Meta Ads, Google), reportes analíticos de inversión y control de gestión.",
                careerFit: ["Negocios Digitales", "Economía", "Administración"],
                requirements: {
                    mandatory: ["Excel avanzado", "Inglés profesional fluido (excluyente)"],
                    desirable: ["Manejo de Meta Ads o Google Ads", "Experiencia en finanzas"],
                    bonus: ["Power BI o Tableau"]
                },
                salaryGuide: "$55.000 - $70.000 UYU (Full-time)",
                applyUrl: "https://advice.zohorecruit.com/jobs/Careers/731279000017056074",
                isLinkedIn: false,
                isTalentPool: false
            }
        ];