// Base de datos de vacantes laborales y pasantías reales en Uruguay
const JOBS_DB = [
            // --- 4 HORAS (PART-TIME / PASANTÍAS) ---
            {
                id: "linkedin-grant-thornton-ciberseguridad",
                company: "Grant Thornton Uruguay",
                title: "Pasante en Ciberseguridad & Auditoría de Sistemas",
                hours: "4h",
                hoursLabel: "4 horas diarias (Lunes a Viernes)",
                modality: "Híbrido / Presencial",
                modalityKey: "hybrid",
                sector: "consulting",
                sectorLabel: "Consultoría & Auditoría IT",
                location: "Montevideo",
                desc: "Pasantía de 3 meses en la firma internacional Grant Thornton. Carga horaria de 4 horas diarias de lunes a viernes. Relevamiento de procesos tecnológicos, controles de seguridad y soporte analítico.",
                careerFit: ["Negocios Digitales", "Sistemas", "Ingeniería", "Administración"],
                requirements: {
                    mandatory: ["Segundo año universitario aprobado", "Disponibilidad 4 horas diarias"],
                    desirable: ["Interés en ciberseguridad y auditoría", "Manejo de herramientas analíticas"],
                    bonus: ["Conocimientos de bases de datos", "Inglés intermedio"]
                },
                salaryGuide: "$22.000 - $28.000 UYU (Pasantía 4h)",
                applyUrl: "https://uy.linkedin.com/jobs/view/pasante-en-ciberseguridad-at-grant-thornton-uruguay-4464220434",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "linkedin-prota-admin-parttime",
                company: "Prota (Consultora RRHH)",
                title: "Administrativa Jr Part-Time (4 a 6 horas)",
                hours: "4h",
                hoursLabel: "4 a 6 horas (A convenir de 9 a 18 hs)",
                modality: "Presencial (Centro)",
                modalityKey: "presential",
                sector: "consulting",
                sectorLabel: "Administración & Soporte",
                location: "Montevideo Centro",
                desc: "Puesto Part-Time de 4 a 6 horas diarias de lunes a viernes coordinables. Contrato a término por 1 año con opción a renovación. Tareas: facturación, planillas de cálculo y archivo.",
                careerFit: ["Administración", "Ciencias Económicas", "Negocios Digitales"],
                requirements: {
                    mandatory: ["Estudiante universitario de Administración o carreras afines", "Manejo de Excel"],
                    desirable: ["Inglés intermedio", "Experiencia previa administrativa"],
                    bonus: ["Manejo de ERP o herramientas contables"]
                },
                salaryGuide: "$24.000 - $32.000 UYU (según horas acordadas)",
                applyUrl: "https://uy.linkedin.com/jobs/view/administrativa-part-time-at-prota-4465221749",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "linkedin-bestseller-student-worker",
                company: "BESTSELLER (Multinacional Retail)",
                title: "Student Worker (Comercial & Base de Datos)",
                hours: "4h",
                hoursLabel: "Part-Time / Horario Estudiante",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "retail",
                sectorLabel: "Retail & Moda Global",
                location: "Montevideo",
                desc: "Vacante Part-Time en BESTSELLER (Jack & Jones, Only, Vero Moda). Soporte al área comercial en actualización de bases de datos, generación de reportes y carga de órdenes.",
                careerFit: ["Negocios Digitales", "Administración", "Economía", "Ingeniería"],
                requirements: {
                    mandatory: ["Estudiante de 1er o 2do año universitario", "Dominio de Excel"],
                    desirable: ["Inglés intermedio (compañía internacional)", "Habilidades de reporte"],
                    bonus: ["Conocimiento de retail o e-commerce"]
                },
                salaryGuide: "$26.000 - $32.000 UYU (Régimen estudiante)",
                applyUrl: "https://uy.linkedin.com/jobs/view/student-worker-contrato-a-t%C3%A9rmino-at-bestseller-4462451747",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "ort-portal-empleo",
                company: "Universidad ORT Uruguay",
                title: "Bolsa de Empleo & Pasantías Exclusivas para Alumnos ORT",
                hours: "4h",
                hoursLabel: "4 a 6 horas (Convenios Académicos)",
                modality: "Presencial / Híbrido",
                modalityKey: "presential",
                sector: "univ",
                sectorLabel: "Bolsa Universitaria",
                location: "Montevideo",
                desc: "Portal oficial de convenios de pasantía académica de ORT Uruguay. Acceso exclusivo a ofertas part-time de empresas socias que coordinan horarios con la facultad.",
                careerFit: ["Negocios Digitales", "Sistemas", "Administración", "Analítica"],
                requirements: {
                    mandatory: ["Ser estudiante activo o graduado de Universidad ORT Uruguay"],
                    desirable: ["Escolaridad destacada"],
                    bonus: ["Nivel B2 de inglés"]
                },
                salaryGuide: "Regulado por convenios universitarios de pasantía",
                applyUrl: "https://empleo.ort.edu.uy/",
                isLinkedIn: false,
                isTalentPool: true
            },

            // --- 6 HORAS (MEDIA JORNADA / BANCA & TECH) ---
            {
                id: "linkedin-pento-ai-trainee",
                company: "Pento (AI & Software)",
                title: "AI Developer Trainee — 6 horas diarias",
                hours: "6h",
                hoursLabel: "6 horas diarias (Modalidad Híbrida)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "tech",
                sectorLabel: "Tecnología & IA",
                location: "Montevideo",
                desc: "Programa formativo Trainee de 6 horas diarias en empresa enfocada en soluciones de inteligencia artificial. Aprendizaje práctico en modelos, desarrollo y analítica de datos.",
                careerFit: ["Negocios Digitales", "Sistemas", "Ciencia de Datos", "Ingeniería"],
                requirements: {
                    mandatory: ["Estudiante universitario activo", "Fundamentos de programación o datos", "Inglés intermedio/avanzado"],
                    desirable: ["Nociones de Python", "Curiosidad por IA generativa"],
                    bonus: ["Proyectos personales o GitHub"]
                },
                salaryGuide: "$30.000 - $38.000 UYU (Trainee 6h)",
                applyUrl: "https://uy.linkedin.com/jobs/view/ai-developer-trainee-at-pento-4465228447",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "linkedin-quantik-pasante-ti",
                company: "Quantik Group",
                title: "Pasante de TI & Soporte de Plataformas — 6 horas",
                hours: "6h",
                hoursLabel: "6 horas diarias (Lunes a Viernes)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "tech",
                sectorLabel: "Telecomunicaciones & Software",
                location: "Montevideo",
                desc: "Pasantía de 6 horas diarias de lunes a viernes en Quantik Group. Atención a usuarios, soporte sobre plataformas digitales y resolución de incidentes operativos.",
                careerFit: ["Sistemas", "Negocios Digitales", "Tecnología"],
                requirements: {
                    mandatory: ["Estudiante de carreras tecnológicas o afines", "Disponibilidad 6 horas"],
                    desirable: ["Sistemas operativos Windows", "Vocación de servicio"],
                    bonus: ["Redes básicas o scripting"]
                },
                salaryGuide: "$28.000 - $35.000 UYU",
                applyUrl: "https://uy.linkedin.com/jobs/view/pasante-de-ti-at-quantik-group-4461373330",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "linkedin-pwc-junior-auditoria",
                company: "PwC Uruguay",
                title: "Junior — Auditoría Externa (Régimen Part-Time)",
                hours: "6h",
                hoursLabel: "6 horas / Part-time formal",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "consulting",
                sectorLabel: "Consultoría & Auditoría",
                location: "Montevideo",
                desc: "Puesto Part-Time formal en PwC Uruguay para estudiantes universitarios con licencias de estudio. Revisión analítica de operaciones, análisis de procesos y control interno.",
                careerFit: ["Contabilidad", "Administración", "Economía", "Negocios"],
                requirements: {
                    mandatory: ["Estudiante universitario con al menos 50% de avance académico", "No requiere experiencia previa"],
                    desirable: ["Inglés intermedio", "Manejo fluido de Excel"],
                    bonus: ["Capacidad analítica y trabajo en equipo"]
                },
                salaryGuide: "$32.000 - $42.000 UYU + Beneficios Big Four",
                applyUrl: "https://uy.linkedin.com/jobs/view/junior-auditor%C3%ADa-externa-contable-at-pwc-uruguay-4465656096",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "linkedin-meli-customer-experience",
                company: "Mercado Libre Uruguay",
                title: "Representante de Customer Experience — 6 horas",
                hours: "6h",
                hoursLabel: "6 horas diarias (Turno fijo)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "tech",
                sectorLabel: "E-commerce & Fintech",
                location: "WTC Montevideo",
                desc: "Atención y soporte a usuarios de Mercado Libre y Mercado Pago en WTC Free Zone. Resolución de consultas sobre pagos digitales, cobros y envíos.",
                careerFit: ["Negocios Digitales", "Administración", "Comunicación"],
                requirements: {
                    mandatory: ["Secundario completo / estudiante universitario", "Disponibilidad 6 horas"],
                    desirable: ["Excelente redacción y empatía", "Manejo de herramientas digitales"],
                    bonus: ["Experiencia en plataformas de e-commerce o atención"]
                },
                salaryGuide: "$35.000 - $45.000 UYU + Almuerzo y prepaga",
                applyUrl: "https://uy.linkedin.com/jobs/view/representante-de-customer-experience-at-mercado-libre-4454696054",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "linkedin-rua-operador-telefonico",
                company: "RUA Asistencia",
                title: "Operador de Servicios & Asistencia — 6 horas",
                hours: "6h",
                hoursLabel: "6 horas diarias (Horario fijo)",
                modality: "Presencial",
                modalityKey: "presential",
                sector: "retail",
                sectorLabel: "Servicios Corporativos",
                location: "Montevideo",
                desc: "Jornada fija de 6 horas diarias para atención y coordinación de servicios solicitados por socios. Seguimiento de casos en plataformas informáticas.",
                careerFit: ["Administración", "General"],
                requirements: {
                    mandatory: ["Disponibilidad 6 horas diarias", "Manejo básico de Office"],
                    desirable: ["Experiencia en atención telefónica"],
                    bonus: ["Resolución rápida de incidentes"]
                },
                salaryGuide: "$25.000 - $30.000 UYU",
                applyUrl: "https://uy.linkedin.com/jobs/view/operador-telef%C3%B3nico-call-center-at-rua-asistencia-4466738461",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "itau-base-talentos",
                company: "Banco Itaú Uruguay",
                title: "Base de Talentos: Postulación Espontánea (Jornada 6h)",
                hours: "6h",
                hoursLabel: "6 horas (Jornada bancaria estándar)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "bank",
                sectorLabel: "Banca & Finanzas",
                location: "Montevideo",
                desc: "Canal oficial para ingresar CV al sistema de Recursos Humanos de Itaú para futuras vacantes de 6 horas en áreas comerciales y operativas.",
                careerFit: ["Ciencias Económicas", "Negocios Digitales", "Administración"],
                requirements: {
                    mandatory: ["Estudiante universitario activo"],
                    desirable: ["Manejo de Excel y orientación analítica"],
                    bonus: ["Inglés profesional"]
                },
                salaryGuide: "Escalafón bancario AEBU (6 horas)",
                applyUrl: "https://www.itau.com.uy/inst/trabajaConNosotros.html",
                isLinkedIn: false,
                isTalentPool: true
            },
            {
                id: "dlocal-careers-montevideo",
                company: "dLocal (Fintech Global)",
                title: "Portal de Carreras & Pasantías Fintech Montevideo",
                hours: "6h",
                hoursLabel: "Flexible / Estudiantes (6h - 8h)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "tech",
                sectorLabel: "Fintech & Pagos Digitales",
                location: "Montevideo",
                desc: "Portal oficial del unicornio fintech uruguayo. Oportunidades en operaciones cross-border, conciliaciones bancarias y analítica de datos.",
                careerFit: ["Negocios Digitales", "Economía", "Sistemas", "Ingeniería"],
                requirements: {
                    mandatory: ["Inglés avanzado (ambiente multinacional)", "Afinidad cuantitativa"],
                    desirable: ["Manejo de SQL o Power BI"],
                    bonus: ["Conocimiento de medios de pago"]
                },
                salaryGuide: "Competitivo mercado fintech global",
                applyUrl: "https://www.dlocal.com/careers/",
                isLinkedIn: false,
                isTalentPool: true
            },

            // --- 8 HORAS (TIEMPO COMPLETO) ---
            {
                id: "linkedin-cash-inteligencia-comercial",
                company: "CASH (Sector Financiero)",
                title: "Analista de Inteligencia Comercial — SQL, Power BI, Excel",
                hours: "8h",
                hoursLabel: "8 horas (Tiempo Completo)",
                modality: "Presencial (Ciudad Vieja)",
                modalityKey: "presential",
                sector: "bank",
                sectorLabel: "Finanzas & Analítica",
                location: "Montevideo, Ciudad Vieja",
                desc: "Extracción, análisis y modelado de datos para generar insights comerciales y tableros en Power BI/Tableau. Soporte al área de negocios.",
                careerFit: ["Ciencia de Datos", "Negocios Digitales", "Economía", "Administración"],
                requirements: {
                    mandatory: ["Estudiantes avanzados de carreras cuantitativas", "Dominio de Excel", "Manejo de SQL"],
                    desirable: ["Power BI, Tableau o Looker", "Uso frecuente de herramientas de IA"],
                    bonus: ["Experiencia en sector financiero"]
                },
                salaryGuide: "$50.000 - $65.000 UYU (Full-time)",
                applyUrl: "https://uy.linkedin.com/jobs/view/analista-de-inteligencia-comercial-at-cash-4466412215",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "linkedin-farmashop-people-analytics",
                company: "Farmashop",
                title: "Asistente de People Analytics — Dashboards & KPIs",
                hours: "8h",
                hoursLabel: "8 horas (Tiempo Completo)",
                modality: "Presencial",
                modalityKey: "presential",
                sector: "retail",
                sectorLabel: "Retail & People Analytics",
                location: "Montevideo",
                desc: "Reportes directivos de gestión humana (rotación, ausentismo, productividad), tableros y automatización en el equipo de RRHH.",
                careerFit: ["Ingeniería", "Análisis de Datos", "Negocios Digitales"],
                requirements: {
                    mandatory: ["Estudiante de Ingeniería o Análisis de Datos", "Excel avanzado (excluyente)"],
                    desirable: ["Power BI o Tableau", "Python básico para automatizaciones"],
                    bonus: ["Conocimiento de métricas de personal"]
                },
                salaryGuide: "$45.000 - $55.000 UYU (Full-time)",
                applyUrl: "https://uy.linkedin.com/jobs/view/asistente-de-people-analytics-at-farmashop-4464229669",
                isLinkedIn: true,
                isTalentPool: false
            },
            {
                id: "cpa-ferrere-procesos-negocios",
                company: "CPA Ferrere",
                title: "Analista de Proceso y Negocios (Banca y Tecnología)",
                hours: "8h",
                hoursLabel: "8 horas (Tiempo Completo - 9 a 18 hs)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "consulting",
                sectorLabel: "Consultoría & Procesos",
                location: "Montevideo",
                desc: "Relevamiento y rediseño de procesos operativos para clientes del sistema bancario nacional e internacional en CPA Ferrere (ID 662164).",
                careerFit: ["Administración", "Economía", "Negocios Digitales", "Ingeniería"],
                requirements: {
                    mandatory: ["Estudiante avanzado o graduado universitario", "Disponibilidad 9 a 18 hs"],
                    desirable: ["Metodologías de procesos (BPM)", "Excel avanzado"],
                    bonus: ["Experiencia bancaria previa"]
                },
                salaryGuide: "$50.000 - $65.000 UYU (Full-time)",
                applyUrl: "https://talento.cpaferrere.com/jobs/662164-analista-de-proceso-y-negocios-banca-y-tecnologia",
                isLinkedIn: false,
                isTalentPool: false
            },
            {
                id: "cpa-ferrere-analista-jr-banca-tech",
                company: "CPA Ferrere",
                title: "Analista Junior en Banca y Tecnología",
                hours: "8h",
                hoursLabel: "8 horas (Tiempo Completo)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "consulting",
                sectorLabel: "Consultoría & Banca",
                location: "Montevideo",
                desc: "Relevamiento de requerimientos con clientes bancarios, testing funcional y apoyo en transformación tecnológica en CPA Ferrere (ID 696910).",
                careerFit: ["Administración", "Contabilidad", "Negocios Digitales"],
                requirements: {
                    mandatory: ["Estudiante avanzado de Ciencias Económicas", "Inglés intermedio/avanzado"],
                    desirable: ["Testing funcional o software bancario"],
                    bonus: ["Excel avanzado"]
                },
                salaryGuide: "$45.000 - $60.000 UYU (Full-time)",
                applyUrl: "https://talento.cpaferrere.com/jobs/696910-analista-junior-en-banca-y-tecnologia",
                isLinkedIn: false,
                isTalentPool: false
            },
            {
                id: "buscojobs-analista-funcional-nexit",
                company: "Nexit (vía BuscoJobs)",
                title: "Analista Funcional Jr (ERP & Consultoría)",
                hours: "8h",
                hoursLabel: "8 horas (Tiempo Completo: 9 a 18 hs)",
                modality: "Presencial / Híbrido",
                modalityKey: "presential",
                sector: "consulting",
                sectorLabel: "Consultoría & ERP",
                location: "Montevideo",
                desc: "Relevamiento de necesidades del cliente corporativo, parametrización y soporte sobre módulos de software de gestión ERP (ID 274020).",
                careerFit: ["Administración", "Negocios Digitales", "Contabilidad"],
                requirements: {
                    mandatory: ["Disponibilidad 9 a 18 hs", "Formación en administración o negocios"],
                    desirable: ["Nociones de sistemas ERP", "Excel analítico"],
                    bonus: ["Capacidad pedagógica con usuarios"]
                },
                salaryGuide: "$40.000 - $52.000 UYU (Full-time)",
                applyUrl: "https://www.buscojobs.com.uy/analista-funcional-jr-contador-lic-en-administracion-en-montevideo-ID-274020",
                isLinkedIn: false,
                isTalentPool: false
            },
            {
                id: "buscojobs-urudata-comercial-jr",
                company: "Urudata (vía BuscoJobs)",
                title: "Ejecutivo Comercial Junior / Business Tech",
                hours: "8h",
                hoursLabel: "8 horas (Tiempo Completo: 9 a 18 hs)",
                modality: "Presencial / Híbrido",
                modalityKey: "presential",
                sector: "tech",
                sectorLabel: "Tecnología Corporativa",
                location: "Montevideo",
                desc: "Gestión de cartera de clientes corporativos B2B y elaboración de propuestas de servicios de infraestructura IT (ID 276252).",
                careerFit: ["Negocios Digitales", "Administración", "Marketing"],
                requirements: {
                    mandatory: ["Perfil comercial B2B", "Disponibilidad 9 a 18 hs"],
                    desirable: ["Conocimiento de servicios cloud e IT"],
                    bonus: ["Habilidades de negociación"]
                },
                salaryGuide: "$42.000 - $55.000 UYU + Comisiones comerciales",
                applyUrl: "https://www.buscojobs.com.uy/ejecutivo-comercial-junior-en-montevideo-ID-276252",
                isLinkedIn: false,
                isTalentPool: false
            },
            {
                id: "advice-digital-media-finance",
                company: "Advice Recursos Humanos",
                title: "Digital Media Finance Analyst",
                hours: "8h",
                hoursLabel: "8 horas (Tiempo Completo)",
                modality: "Híbrido",
                modalityKey: "hybrid",
                sector: "consulting",
                sectorLabel: "Consultora & Selección",
                location: "Montevideo",
                desc: "Conciliaciones financieras de plataformas de medios digitales (Meta Ads, Google), reportes analíticos de inversión y control de gestión.",
                careerFit: ["Negocios Digitales", "Economía", "Administración"],
                requirements: {
                    mandatory: ["Excel avanzado", "Inglés profesional fluido (excluyente)"],
                    desirable: ["Manejo de Meta Ads o Google Ads", "Experiencia en finanzas"],
                    bonus: ["Power BI o Tableau"]
                },
                salaryGuide: "$55.000 - $70.000 UYU (Full-time)",
                applyUrl: "https://advice.zohorecruit.com/jobs/Careers/731279000017056074",
                isLinkedIn: false,
                isTalentPool: false
            }
        ];
